### ISSUE TITLE
Documenting Arrays/Hashes

### ISSUE THREAD

**Issue by curtisolson** [zipmark/rspec_api_documentation#112]
I have a similar problem to this issue: https://github.com/zipmark/rspec_api_documentation/issues/79

Except I have multiple levels. In my POST I'm able to use scope for the first hash, but then that hash has an array

container_field has hash custom_fields
Within custom_fields there are name/value pairs passed in.

```
curl -X POST -H Cache-Control:no-cache -H Postman-Token:897136cd-8f79-9327-9a2d-598e53cf1541 -F container_field[custom_fields][0][name]=first field -F container_field[custom_fields[0][value]=first value -F container_field[custom_fields][1][name]=second field -F container_field[custom_fields[1][value]=second value?auth_token=RXhYXWCeVMwbgZzjp3AM
```

How would I write that as parameter and let statements?

**Comment by lakesare** [comment]
what is the way to solve it now? having the same issue.

**Comment by rvirani1** [comment]
+1

**Comment by ilnurnasyrov** [comment]
The same. I have array of hashes.
