### ISSUE TITLE
Respect describe/context blocks?

### ISSUE THREAD

**Issue by AlexParamonov** [zipmark/rspec_api_documentation#160]
I have an issue when generate docs for structure like this:

``` ruby
resource "Users" do
  get "/users" do
    include_context :json
    it_behaves_like :ok_request
  end

  get "/users/:id" do
    include_context :json
    it_behaves_like :ok_request
  end
end
```

While the log produces:

```
GET /users
    * returns JSON
  behaves like ok_request
    * has status 200
GET /users/:id
    * returns JSON
  behaves like ok_request
    * has status 200
```

the files are generated with the same name and overwrite each other. Nesting is not preserved.

Seems that I don't understand how to use it correctly to produce nice documentation.
In this case an explanation in README would be great.

You can see the entire specs below:
https://github.com/crasome/mysterious-api/blob/2a88c810935dfff04e7f105e44baba4e299a65bd/spec/acceptance/users_spec.rb

**Comment by myabc** [comment]
I've begun working on the option to include context descriptions in the examples - https://github.com/zipmark/rspec_api_documentation/pull/283 -, but the solution could use some feedback.
