### ISSUE TITLE
rspec-expectations conflict

### ISSUE THREAD

**Issue by gdlx** [zipmark/rspec_api_documentation#161]
Hi,

I'm using RSpec 3.1.0 and there's a gem version conflict on `rspec-expectations` with `rspec_api_documentation`:

```
Bundler could not find compatible versions for gem "rspec-expectations":
  In Gemfile:
    rspec_api_documentation (~> 4.1.0) ruby depends on
      rspec (>= 3.0.0, ~> 3.0.0) ruby depends on
        rspec-expectations (~> 3.0.0) ruby

    rspec-rails (~> 3.1.0) ruby depends on
      rspec-expectations (3.1.0)
```

Not sure how to fix this since it's because of a rspec dependancy. Maybe  you should not provide a `Gemfile.lock` since it seems to be the root cause ? (https://github.com/zipmark/rspec_api_documentation/blob/master/Gemfile.lock#L83)

**Comment by richardrails** [comment]
Bundler could not find compatible versions for gem "rspec-expectations":
  In snapshot (Gemfile.lock):
    rspec-expectations (= 3.9.0)

  In Gemfile:
    rspec_api_documentation was resolved to 6.1.0, which depends on
      rspec (~> 3.0) was resolved to 3.9.0, which depends on
        rspec-expectations (~> 3.9.0)

    rspec-rails was resolved to 4.0.0.pre, which depends on
      rspec-expectations (= 3.10.0.pre)
