### ISSUE TITLE
Multilevel scope parameters

### ISSUE THREAD

**Issue by JakubRacek** [zipmark/rspec_api_documentation#176]
Hi, just trying to make multilevel scope parameters but I am unable to make it using scope_parameters.
an example code could be:

```ruby
parameter :item_id, "Id of an item to order", required: true
parameter :city, "Address city", required: true

scope_parameters :order, [
  :item_id,
  address: [
    :city
  ]
]
```

Is there a way to define them or is it a feature request?

**Comment by oestrich** [comment]
Closed with #221
