### ISSUE TITLE
Is it possible to manipulating the request before executing the request?

### ISSUE THREAD

**Issue by ekampp** [zipmark/rspec_api_documentation#177]
Hi there. 

Is there a way to manipulate the request object before executing it when running the acceptance tests to generate documentation?

My problem right now is that I want to implement [ApiAuth](https://github.com/mgomes/api_auth) but that requires running `ApiAuth.sign!(request)` on the request object before executing the request, and I'm having a hard time figuring out how to get at the request object when running acceptance specs with the RSpec API Documentation DSL.

I hope someone can help. 

Cheers.

**Comment by SinisterLight** [comment]
@ekampp how exactly you did this ?

**Comment by ekampp** [comment]
It took me some time to understand and figure out, but follow the advice @oestrich gave. I don't have my solution at hand, since the project didn't amount to anything.
