### ISSUE TITLE
REOPENING OLD ISSUE : Undefined method `documentations' for RspecApiDocumentation

### ISSUE THREAD

**Issue by ACPK** [zipmark/rspec_api_documentation#188]
RspecApiDocumentation::ApiFormatter
Generating API Docs
No examples found.
/Users/andrewcharleskelley/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec_api_documentation-4.3.0/lib/rspec_api_documentation/api_formatter.rb:16:in `start': undefined method `documentations' for RspecApiDocumentation:Module (NoMethodError)

**Comment by ACPK** [comment]
Another user had reported this here: https://github.com/zipmark/rspec_api_documentation/issues/64

**Comment by oestrich** [comment]
Since it says "No examples found", do you have a `spec/acceptance` folder that has your RAD specs in?

**Comment by ACPK** [comment]
@oestrich My tests are all is spec/requests/v1/give_it_a_name_spec.rb.

Do I have to write new tests for rspec_api_documentation?

**Comment by oestrich** [comment]
The rake command you're running looks inside of `spec/acceptance`. https://github.com/zipmark/rspec_api_documentation/blob/master/lib/tasks/docs.rake#L5 

Make your own task that does the same but points in the `requests` folder.

**Comment by oestrich** [comment]
Closing due to age.
