### ISSUE TITLE
support for type validation,  param_groups?

### ISSUE THREAD

**Issue by mooreniemi** [zipmark/rspec_api_documentation#189]
I love rspec_api_documentation but it lacks some things apipie has which I sometimes want. The big ones are type checking (this param should be a Fixnum, etc) and reusable param_groups (so I don't have to respecify parameter calls  in each spec block). Any plans to add these? Interest if I tried to send a pull request in this direction?

**Comment by oestrich** [comment]
I am definitely interested in param groups. Could you explain what you mean by type checking a bit more? Would it be any different than just `expect`ing the response to be the format you want? Maybe we could pull in JSON schema for this?

**Comment by mooreniemi** [comment]
@oestrich Thanks for your quick reply! 

I mean

`parameter :start_time, "New reservation start time"` necessitates me doing something like `let(:start_time) { <some bogus date here> }`

it'd be cool if i could do `parameter :start_time, DateTime, "New instance of valid time"` and have the gem generate the data to put into raw_post.

**Comment by mooreniemi** [comment]
On the other side, I feel like apipie mixes concerns with this, and allows you to do validators by type on params (`param :session, String, :desc => "user is logged in", :required => true`) because it is living in the actually executed code (thus it is becoming part of the actual codebase now).

**Comment by oestrich** [comment]
Closing due to age. For the param_groups I've gotten around this by having a shared context that holds parameter calls I use a lot.

```ruby
shared_context :pagination do
  parameter :page, "Page", :default => 1
  parameter :per, "Number of items per page", :default => 50
end
```

Then to use:

```ruby
resource "Orders" do
  get "/orders" do
    include_context :pagination

    parameter :since, "List orders since..."
    # ...
  end
end
```
