### ISSUE TITLE
how to use VCR?

### ISSUE THREAD

**Issue by AlexParamonov** [zipmark/rspec_api_documentation#195]
Hello.

How can I use the VCR or other tool to not hit the network when running rspec api documentation specs?

It raises VCR::Errors::UnhandledHTTPRequestError correctly, but VCR.use_cassette has no effect in example specs.

**Comment by AlexParamonov** [comment]
I had some errors regarding VCR configuration for acceptance specs.
Now it works fine.
FYI I added VcrDoRequest helper. to reduce manual do_request overwrites.

``` ruby 
get "/channels/:id" do
  include SpecHelpers::VcrDoRequest[:channels]
  # ...
end
```

``` ruby
module SpecHelpers
  module VcrDoRequest
    def self.[](cassette_name)
      Module.new.tap do |included_module|
        included_module.send :define_method, :do_request do |*args|
          VCR.use_cassette(cassette_name, record: :new_episodes) { super *args }
        end
      end
    end
  end
end
```

**Comment by citizen428** [comment]
This doesn't seem to work for me. Neither did my other attempts (like aliasing `do_request` and calling the original method from within a `use_cassette` block. Any ideas?

**Comment by citizen428** [comment]
I know this issue is closed, but I just wanted to add how we solved the same problem (unlike @AlexParamonov we actually went for a monkey-patch, otherwise it's pretty similar):

```
module RspecApiDocumentation::DSL::Endpoint
  alias_method :orig_do_request, :do_request

  VCR_OPTIONS = { match_requests_on: [:method, :path] }

  def do_request(*args)
    VCR.use_cassette(cassette_path, VCR_OPTIONS) { orig_do_request(*args) }
  end

  private

  def cassette_path
    resource = example.metadata[:resource_name]
    name = example.metadata[:description].underscore
    "acceptance/#{resource}/#{name}"
  end
end
```

**Comment by vanburg** [comment]
is this the best way still?
