### ISSUE TITLE
Specifying a parameter named ':text' throws an error

### ISSUE THREAD

**Issue by brettchalupa** [zipmark/rspec_api_documentation#203]
While specifying a parameter for an example, I discovered that naming a parameter `:text`causes the following error to be thrown:

```
Failure/Error: do_request(
Capybara::ElementNotFound:
  Unable to find xpath "/html"
```

The parameter line:

``` ruby
parameter :text, 'Content of the comment', required: true
```

If I change the `:text` to anything, like `:tex` or `:texty`, the error does not get thrown.

Any thoughts on what may be causing this or how to work around it?

The example in more detail:

``` ruby
resource 'Comments', document: :v2 do
  post '/api/v2/comments' do
    parameter :moment_id, 'ID of the moment to be commented on', required: true
    parameter :text, 'Content of the comment', required: true

    let(:moment) { moments(:photo) }

    example 'Comment on a moment' do
      expect do
        do_request(
          comment: {
            moment_id: moment.id,
            text: 'Too cute'
          }
        )
      end.to change { Comment.count }.by(1)

      expect(moment.comments).to include(Comment.where(text: 'Too cute').first)
      expect(status).to be(200)
    end
  end
end
```

Thank you!

**Comment by oestrich** [comment]
Sorry for taking a bit to get to this. My guess is you have something else `let` as `text`, looks like capybara has a `text` DSL method. The DSL tries to pull in everything it can before merging in the extra parameters passed in to `do_request`. If you do the following it should start working again:

``` ruby
let(:text) { nil }
```

**Comment by brettchalupa** [comment]
@oestrich thanks a bunch - I appreciate it. Will close this.
