### ISSUE TITLE
Docs generation fails image is returned as part of a spec

### ISSUE THREAD

**Issue by nicolo** [zipmark/rspec_api_documentation#205]
I'm getting the following error when trying to create documentation for a route that returns a file.
write': "\xFF" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError) when trying to return a jpeg from my api.

This seems to be related
https://github.com/zipmark/rspec_api_documentation/issues/39

**Comment by amedrz** [comment]
Same here, I have:
````
post "api/attachments" do                                      
  header 'Accept', '*/*'                                                          
  header 'Content-Type', 'multipart/form-data'                                    
                                                                                
  parameter :attachment, "Attachment", "Type" => "Multipart/Form-data"            

  example "add an attachment" do                                                  
    do_request(attachments: { attachment: attachment })
    expect(response_status).to eq(201)                                            
  end                                                                             
end
````
Where `attachment` is an instance of `Rack::Test::UploadedFile`

And I'm getting:
````
Failure/Error: do_request(attachments:
     Encoding::UndefinedConversionError:
       "\x89" from ASCII-8BIT to UTF-8
````

Any hints? @nicolo @oestrich 

I'm on Rails 4.1.9 and rspec_api_documentation 4.4.0

Thanks!

**Comment by bforma** [comment]
As a workaround, I've replaced the contents of binaries files with a string like "Contents of a JPEG image". This also documents quite well. Perhaps you can use this.

**Comment by risinglf** [comment]
Hi @bforma can I ask you have did you do that? Thank you so much.

**Comment by bforma** [comment]
Hi @risinglf, just create a `.jpg` file with the following contents: `Contents of a JPEG image`. Hope this helps.

**Comment by risinglf** [comment]
thanks @bforma my problem is on the response, that it's a PDF file. Any ideas to handle it? Thank you.

**Comment by oestrich** [comment]
@risinglf Last week I pushed up changes that should sniff out binary data and replace it with `[binary data]`, can you update your Gemfile to master and see if that fixes your problem? If it does I'll go ahead and release a new version.

**Comment by oestrich** [comment]
Closing because this should be fixed in newer versions. See [client_base.rb](https://github.com/zipmark/rspec_api_documentation/blob/master/lib/rspec_api_documentation/client_base.rb#L98)
