### ISSUE TITLE
undefined method `resource' for main:Object (NoMethodError)

### ISSUE THREAD

**Issue by waleedasif322** [zipmark/rspec_api_documentation#206]
Hi, I'm trying to use this gem, however, I get this error: `undefined method 'resource' for main:Object (NoMethodError)`

I tried using the example app and doing a similar setup to my app (I'm using a gem called `api-versions`) and it worked perfectly, but on my own app, this is the stack trace I get when I run `bundle exec rake docs:generate`:

    /home/waleed/app/spec/acceptance/authenticates_spec.rb:3:in `<top (required)>': undefined method `resource' for main:Object (NoMethodError)
	from /home/waleed/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
	from /home/waleed/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
	from /home/waleed/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
	from /home/waleed/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
	from /home/waleed/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
	from /home/waleed/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
	from /home/waleed/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
	from /home/waleed/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
	from /home/waleed/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.3/exe/rspec:4:in `<main>'
    /usr/bin/ruby1.9.1 -I/home/waleed/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.3/lib:/home/waleed/.rvm/gems/ruby-2.1.2/gems/rspec-support-3.2.2/lib /home/waleed/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.3/exe/rspec --pattern spec/acceptance/\*\*/\*_spec.rb --format RspecApiDocumentation::ApiFormatter failed

My spec looks like this:
````RUBY
require 'acceptance_helper'
resource "Authenticates" do
    post "/api/authenticates" do

    end
    get "/api/authenticates" do

    end

    put "/api/authenticates" do

    end

    delete "api/authenticates" do

    end
end
````

**Comment by oestrich** [comment]
Did you `require 'rspec_api_documentation/dsl'` in `acceptance_helper`?

**Comment by waleedasif322** [comment]
Hey thanks for getting back to me, yes I did, `acceptance_helper` looks like this:
```
require 'rails_helper'
require 'spec_helper'
require 'rspec_api_documentation'
require 'rspec_api_documentation/dsl'

RspecApiDocumentation.configure do |config|
  config.format = [:json, :combined_text, :html]
  config.curl_host = 'http://localhost:3000'
  config.api_name = "NexHealth API"
end
```

**Comment by Jesterovskiy** [comment]
@waleedasif322 try to use `RSpec.resource`

**Comment by cmason** [comment]
@waleedasif322 I was getting the same error. Commenting out  `config.disable_monkey_patching!` in spec_helper.rb solved it for me.

**Comment by oestrich** [comment]
Closing due to age

**Comment by Dschee** [comment]
I just had a similar problem and really got confused. Neither the 'resource' got recognized nor the `rake docs:generate` command. After finding this thread it turned out that we had `config.disable_monkey_patching!` set in our spec_helper, too. Maybe we should update the docs that this option should not be set or try to add a fallback where people have to integrate the required monkey-patched features manually?

**Comment by nidhi-soni1104** [comment]
I am trying to remove rspec_api_documentation gem and still receiving same issue

NoMethodError:
  undefined method `resource' for main:Object
  Did you mean?  rescue
