### ISSUE TITLE
Include resource ID in PUT/PATCH body

### ISSUE THREAD

**Issue by bjubinville** [zipmark/rspec_api_documentation#208]
Hi,

Is there a way to include the ID of a resource in the the body of a PUT or PATCH?  I've tried the following, but to no avail:

```
parameter :id, 'ID of the resource', required: true
```

This is required for conformity to the emerging jsonapi spec: http://jsonapi.org/format/#crud-updating

Thanks.

**Comment by oestrich** [comment]
I'm guessing you have `:id` in the route? The DSL strips out any parameters in the URL from the automatic body. For jsonapi you will almost certainly have to fiddle with the default post body.

```ruby
let(:raw_post) do
  # Do custom request here
end
```

**Comment by damienbrz** [comment]
I have the same issue here

I have the following code:

```ruby
class Post < ActiveRecord::Base
  belongs_to :user
end
```

```ruby
class PostResource < BaseResource
    has_one :user

    attribute :content
    attribute :posted_at
end
```

```ruby
class PostsController < ApplicationController
end
```

When writing my specs, I always face the following issue with the PATCH method:
`{"errors":[{"title":"A key is required","detail":"The resource object does not contain a key.","id":null,"href":null,"code":109,"source":null,"links":null,"status":"400"}]}`

The params received in the update method in my controller are the following:
`{"data"=>{"type"=>"posts", "attributes"=>{"content"=>"Hello"}}, "controller"=>"v1/posts", "action"=>"update", "id"=>"5"}`

It seems that it's missing the `id` property in the `data` hash.

Follow is my spec:

```ruby
patch "/v1/posts/:id" do
    let(:persisted_post) { FactoryGirl.create(:post) }

    parameter "id", <<-DESC, required: true
      The id of the user.
    DESC

    let(:id) { persisted_post.id }
    let(:content) { "Hello" }
    
    include_context "post parameters"

    example_request "Update a post" do
      expect(status).to eq 200
      post = JSON.parse(response_body)
      expect(post["data"]["attributes"]["content"]).to eq content
    end
end
```

**Comment by oestrich** [comment]
@damienbrz What does the `post parameters` context expand to?

Closing for now.

**Comment by npendery** [comment]
Was this ever resolved? I am running into the issue as well

**Comment by utilityboy** [comment]
I ended up creating a helper module for this:

```
include JsonapiAcceptanceHelpers

  put "#{endpoint}/:id" do
    let!(:my_resource) { FactoryGirl.create(:my_resource) }
    let(:id) { my_resource.id }

    parameter :type, "Type of the resource: #{resource_type}", required: true

    # attributes
    parameter :name, 'Name of the resource', scope: :attributes

    let(:type) { resource_type }
    let(:name) { 'Updated Resource' }

    let(:raw_post) { resource_update_payload }

    example_request 'Updating a resource' do
      expect(response_status).to eq(200)
      expect(attributes['name']).to eq(name)
    end
  end

module JsonapiAcceptanceHelpers

...

  def resource_update_payload
    payload = {
      data: params
    }
    # currently need to manually add the id to the payload for jsonapi conformance
    # https://github.com/zipmark/rspec_api_documentation/issues/208
    payload[:data][:id] = id.to_s
    payload.to_json
  end

...

end
...

**Comment by npendery** [comment]
Sweet, thanks @utilityboy!!
