### ISSUE TITLE
How to set diffferent value for same parameter name with different scope?

### ISSUE THREAD

**Issue by anujaware** [zipmark/rspec_api_documentation#214]
Suppose I have a nested form and have 'email' field for parent and child model also if I want to pass parameters for two child objects with different email address. Is there a way to do this?

**Comment by thomassnielsen** [comment]
We're seeing the same issue. We're following the [jsonapi](http://jsonapi.org) spec, which requires related resources to be nested inside a response tag. Example:

```json
{
    "data":{
        "type":"cart-items",
        "attributes":{
            "count":"1",
            "product-iteration-id":2
        },
        "relationships":{
            "product-variant":{
                "data": {
                    "type":"product-variants",
                    "id":3
                }
            },
            "user":{
                "data": {
                    "type":"users",
                    "id":4
                }
            }
        }
    }
}
```

This leaves us with a problem when creating params, as we would need multiple `id`s and `type`s with different scopes. #221 lets us scope them correctly, but we're still having the issue with them being called the same thing.

To illustrate the problem:

```ruby
parameter :id, "Id of product variant", scope: [:relationships, :variant, :data]
parameter :id, "The id of the user (checked against auth token)", scope: [:relationships, :user, :data]
parameter :type, "Id of product variant", scope: [:relationships, :variant, :data]
parameter :type, "Id of product variant", scope: [:relationships, : user, :data]
```

I'm not familiar enough with the internals of rspec_api_documentation to suggest a technical solution, but from a usage perspective it would be nice if we could define the data and parameter together. Something like:

```ruby
parameter [:relationships, :user, :data, :id], "Id of the user", { user.id }
```

**Comment by cover** [comment]
#221 also takes care of setting parameters with the same name (and different scopes). You just need to prefix the scope:

```
let(:relationships_variant_data_id) { 111 }
let(:relationships_user_data_id) { 222 }
let(:relationships_variant_data_type) { 'variant' }
let(:relationships_user_data_type) { 'user' }
```

To set the parameter value it looks for a method called `scope_parameter` and if it doesn't exists it tries with `parameter`, mostly in order to avoid breaking existing apps that use scopes

**Comment by thomassnielsen** [comment]
Will it work with underscored_names? (I don't see how it will know the difference between scopes and variable_names?) What about "dasherized-names"? We're using strings in our `let`s because we need dasherized names, and that seems to work.

Example:
```ruby
parameter "display-addr", "The address of the shop", required: false, scope: :attributes
let("display-addr") { "Test shop street 1" }
```

**Comment by cover** [comment]
Yes, it does.

```
parameter :resource_id, "Id of product variant", scope: [:data, :relationships, :variant, :data]
```

will look for `data_relationships_variant_data_resource_id` and fallback to `resource_id`.
When it [builds the hash](https://github.com/zipmark/rspec_api_documentation/blob/master/lib/rspec_api_documentation/dsl/endpoint.rb#L164) it passes an array with all the keys (scope + param name). The last one is always the param name and the previous one the scope making it working with underscore names

I haven't tried with dasherized names, but if `let("display-addr")` works then the scoped `let("attributes_display-addr")` should work as well. The scope and the parameter name are [joined using the underscore](https://github.com/zipmark/rspec_api_documentation/blob/master/lib/rspec_api_documentation/dsl/endpoint.rb#L154)

**Comment by thomassnielsen** [comment]
Thanks a lot, especially for linking to the relevant code :+1: 
I'll give it a try once our specs are past their current `pending` state.

Btw, this should be documented. If nobody else does it I'll throw in a PR once I've verified how it works for us.
