### ISSUE TITLE
Can't declare parameter with name status

### ISSUE THREAD

**Issue by Shwetakale** [zipmark/rspec_api_documentation#215]
I have field in my model with name status which I need as parameter. 

I am declaring it like

    parameter :status, "Task status: 'completed, pending'", required: true,"Type" => "String"

When I declare writing above line I am getting error as:

    Failure/Error: do_request(api_key: user.api_key)
       Rack::Test::Error:
       No response yet. Request a page first.
      # /home/shweta/.rvm/gems/ruby-2.1.2/gems/rack-test-0.6.2/lib/rack/mock_session.rb:56:in `last_response'
      # /home/shweta/.rvm/gems/ruby-2.1.2/gems/rspec_api_documentation-4.4.0/lib/rspec_api_documentation/rack_test_client.rb:4:in `last_response'
      # /home/shweta/.rvm/gems/ruby-2.1.2/gems/rspec_api_documentation-4.4.0/lib/rspec_api_documentation/rack_test_client.rb:20:in `status'
      # ./spec/acceptance/tasks_controller_spec.rb:35:in `block (3 levels) in <top (required)>'

When I remove below line or update parameter name  everything works as expected

    parameter :status, "Task status: 'completed, pending'", required: true,"Type" => "String"

Is this bug or I am missing something?

**Comment by Shwetakale** [comment]
Further Analysis:

Error is coming from

https://github.com/zipmark/rspec_api_documentation/blob/master/lib/rspec_api_documentation/dsl/endpoint.rb

    65: def params
    66:   parameters = example.metadata.fetch(:parameters, {}).inject({}) do |hash, param|
    => 67:     set_param(hash, param)
    68:   end
    69:   parameters.deep_merge!(extra_params)
    70:   parameters
    71: end
In set_params method

     def set_param(hash, param)
       150:   key = param[:name]
       151:   return hash if !respond_to?(key) || in_path?(key)
       152: 
       153:   if param[:scope]
       154:     hash[param[:scope].to_s] ||= {}
       155:     hash[param[:scope].to_s][key] = send(key)
       156:   else
       157:     hash[key] = send(key)
       158:   end
       159: 
       160:   hash
    161: end

Here on line number 151

return hash if !respond_to?(key) || in_path?(key)

    respond_to?(key) returns false for other params but returns true for status

**Comment by oestrich** [comment]
The `status` method is defined by the DSL. You need to call the `disable_dsl_status!` method in your configuration block, [see here](https://github.com/zipmark/rspec_api_documentation/blob/master/lib/rspec_api_documentation/configuration.rb#L109).

**Comment by Shwetakale** [comment]
Thanks @oestrich.  Setting header as

    header "Content-Type", "application/json"

Solved my problem.
