### ISSUE TITLE
Undefined method response_field

### ISSUE THREAD

**Issue by andrewpbrett** [zipmark/rspec_api_documentation#217]
I'm getting the error "undefined method response field" when I generate docs with the following spec. As far as I can tell I'm following the example given in the Readme: 

```ruby
require 'spec_helper'
require 'rspec_api_documentation/dsl'

resource "Search" do
  parameter :q, "String. Query string."
  response_field :products, "Array of products"
  get "/api/v1/search" do
    example "Search for new products" do
      explanation "Returns all products sorted by the newest"
      do_request

      status.should == 200
    end
  end
end
```

**Comment by oestrich** [comment]
Closing for now. Are you still getting this? I will reopen if you are.

**Comment by Guilleves** [comment]
I'm having the same issue. I have followed the example given, and my test looks like this:

    require 'spec_helper'
    require 'rspec_api_documentation/dsl'

    resource "Taxons" do
      post "api/v2/taxons" do
        parameter :uri, "URI of the taxon", :required => true, :scope => :taxon
        response_field :uri, "URI of the taxon", "Type" => "String", :scope => :taxon

        example_request "Create a taxon" do
          status.should == 201
        end
      end
    end

When I try to generate the docs by running rake docs:generate, i get the following error.

`    /PriceAudit/spec/acceptance/api/taxons_spec.rb:75:in 'block (2 levels) in <top (required)>': undefined method 'response_field' for #<Class:0x005592cdd4cc80> (NoMethodError)`

Has anyone experienced the same issue?
