### ISSUE TITLE
parameter :status breaks the do_request

### ISSUE THREAD

**Issue by h55nick** [zipmark/rspec_api_documentation#220]
```
parameter :status
```
in an example will result in:
```
Failure/Error: do_request
  Rack::Test::Error:
  No response yet. Request a page first.
```

if you point me in the right direction happy to help out.

**Comment by oestrich** [comment]
You need to call this configuration option https://github.com/zipmark/rspec_api_documentation/blob/master/lib/rspec_api_documentation/configuration.rb#L109. 

I have also added it to the readme since it wasn't there.

**Comment by h55nick** [comment]
awesome. thanks for helping out! 

We are going to be using this to document our api and will be given some time to contribute back to the project (easy sell with your quick response!). Is there a forum that would be helpful to discuss the contributions that would be most helpful/direction of the project etc?
