### ISSUE TITLE
`parameter` method not working, empty params

### ISSUE THREAD

**Issue by samselikoff** [zipmark/rspec_api_documentation#227]
Brand new to this lib so this may be a silly question, but I can't seem to get the `parameter` method to work.

```rb
require 'rails_helper'
require 'rspec_api_documentation/dsl'

resource 'Countries' do
  get '/v1/countries' do
    parameter :some, "param"

    example 'Listing countries' do
      expect(status).to eq(200)
    end
  end

end
```

When I put a breakpoint in my controller, `params` hash doesn't have the `some` param. However if I do

```rb
require 'rails_helper'
require 'rspec_api_documentation/dsl'

resource 'Countries' do
  get '/v1/countries' do

    example 'Listing countries' do
      do_request(some: 'param')

      expect(status).to eq(200)
    end
  end

end

```

it works. Any ideas?

Thanks for this great lib!

**Comment by oestrich** [comment]
`parameter` by itself only outputs to the documentation. You need to `let(:some) { "thing" }` and the controller will have `params[:some] == "thing"`.

`do_request` passes everything it receives as a parameter so that's why it's working.

**Comment by samselikoff** [comment]
Ah, missed that. Thanks!
