### ISSUE TITLE
Running rake task clears development database

### ISSUE THREAD

**Issue by DavidVII** [zipmark/rspec_api_documentation#228]
After running `rake docs:generate` my database is completely cleared. Similar to how
`rake db:schema:load` clears the db. Is this expected behavior?

**Comment by DavidVII** [comment]
Looks like this may be happening because I didn't specify the test environment while running the rake task.

```rake
rake docs:generate RAILS_ENV=test
```

**Comment by soberstadt** [comment]
I ran into this same issue yesterday. Is there a way to have the rake task run in test Env by default? I am disabling the rake task on our project in the meantime so I don't accidentally do this again.

In Rakefile:

    Rake::Task['docs:generate'].clear
    namespace :docs do
      task :generate => :environment do
        p 'running this will load it as dev mode by default, which will fail'
        p 'run `rspec spec/acceptance --format RspecApiDocumentation::ApiFormatter` instead'
      end
    end

**Comment by oestrich** [comment]
I just tested this on one of my projects and it doesn't clear the test database. We're creating a new RSpec task so it should be set up properly. Is your `spec_helper.rb` or `rails_helper.rb` setup to load the test env by default?

`ENV["RAILS_ENV"] ||= 'test'` is at the top of my `rails_helper.rb` file.

**Comment by soberstadt** [comment]
My issue was that I had database cleaner set to clear my database after each spec suite. I'm assuming that's what @DavidVII was dealing with too. I already have `ENV["RAILS_ENV"] ||= 'test'` in my rails_helper. I added `
abort("The Rails environment is running in #{Rails.env} mode!") if Rails.env.production? || Rails.env.development?` as well and it would abort.

**Comment by DavidVII** [comment]
@soberstadt good eye! It appears that's what happened to me too. At the very least we can guard abort if running in production/development.

**Comment by soberstadt** [comment]
My current Rakefile changes:
```
unless Rails.env.test?
  Rake::Task['docs:generate'].clear
  namespace :docs do
    task generate: :environment do
      p 'running this will load it as dev mode by default, which will fail'
      sh 'RAILS_ENV=test rake docs:generate'
    end
  end
end
```
