### ISSUE TITLE
Need example with login/sign_in (preferably devise)

### ISSUE THREAD

**Issue by sbwoodside** [zipmark/rspec_api_documentation#229]
I'm new to using acceptance tests and most of the methods that I am familiar with to login/sign_in a user before the test aren't working. Where can I find an example of how to do this? I've tried http://kalapun.com/posts/generating-api-docs-from-rspec-tests/ but it glosses over "prefill_db_for_api" without providing a complete example.

**Comment by oestrich** [comment]
Looking at that article, it's just not doing `User.create(...)`. A login endpoint shouldn't be any different than any other test, you'll want to look at creating an order as it will be similar to creating a session https://github.com/zipmark/rspec_api_documentation/blob/master/example/spec/acceptance/orders_spec.rb#L32-L61

**Comment by sbwoodside** [comment]
OK, I think that what I need to do is to have the first test do a login,
and then use the token from that login for subsequent attempts, as in
http://kalapun.com/posts/generating-api-docs-from-rspec-tests/

**Comment by sbwoodside** [comment]
I have posted a gist here: https://gist.github.com/sbwoodside/19d3e033076de2bd1194

The problem now is that I need `post "/users/sign_in" do` to run first. But for some reason `get "/measurements" do` is running first. Which means that it runs without the session cookie.

This API requires sessions in order to do anything. How can I get the login to run first?

**Comment by oestrich** [comment]
Each example is a completely separate thing. They are supposed to run in any order and are independent of each other. See [rspec](https://github.com/rspec/rspec) for more info on this.

Also the `puts` you have is in the wrong context, it's in an `ExampleGroup` not an `Example`.

Here is an example of doing a request with the `Authorization` header.

``` ruby
get "/measurements" do
  header "Authorization", :bearer

  let(:user) { User.create(...) }
  let(:bearer) { "Bearer #{user.token}" }

  example_request "Listing measurements" do
    expect(status).to eq(200)
  end
end
```

If you need to use the cookie, you can just send the header normally. I would advise against this as APIs tend to not use sessions.

``` ruby
get "/measurements" do
  header "Cookie", :cookie

  let(:cookie) { "whatever your cookie header looks like" }

  example_request "Listing measurements" do
    expect(status).to eq(200)
  end
end
```

**Comment by oestrich** [comment]
You almost never need to `let` your own client either. Use the DSL to generate headers for you. The README explains everything you can do in the DSL.

**Comment by sbwoodside** [comment]
Thanks. How do you suggest that I get the sign in example to run before the `get "/measurements"` example? So that I will actually have the cookie.

I have tried using rspec's order configuration, for example with `:order => :defined` and `:order => :random` (https://www.relishapp.com/rspec/rspec-core/docs/configuration/overriding-global-ordering) but in all cases the GET runs before the POST (even if I do multiple runs with the random option, or switch the order in the file).

I don't have any choice as for using sessions right now. This was an architectural decision that was made and of course these things can have a religious flavour to them.

**Comment by sbwoodside** [comment]
I figured out how to sign in.

I needed to follow https://github.com/plataformatec/devise/wiki/How-To:-Test-with-Capybara which explains that you can't use Devise helper methods in request specs, instead you need to use Warden helper methods.

I have a new problem now: the first example works, but subsequent examples fail. The error is `401 Unauthorized` in the test log, and the test output says that `expect(status).to eq(200)` is returning `302`. Here is the code now:

https://gist.github.com/sbwoodside/bbd5c1600d4e0bcc92a6

**Comment by dominicpacquing** [comment]
@sbwoodside have you tried logging in using the client. This works for me
```ruby 
example "Order" do
  no_doc do
      client.post "/users/sign_in", { user: { email: @user.email, password: @user.password } }
  end

  do_request(id: @order.id)
  expect(status).to be == 200
end
```

**Comment by tannakartikey** [comment]
I did it in the following way:
```
 patch '/users.json' do
      parameter :id, "Id of the user", scope: :user
      parameter :current_password, "Password of the user", scope: :user
   
      header "Authorization", :bearer

      let(:user) { create(:user) }

      let(:id) { user.id }
      let(:current_password) { user.password }
      let(:bearer) { "Bearer #{(Doorkeeper::AccessToken.create!(resource_owner_id: user.id)).token}" }

      let(:raw_post) { params.to_json }

      example_request "Update user" do
        user.reload
      end
    end
```
