### ISSUE TITLE
Headers in before blocks don't work

### ISSUE THREAD

**Issue by jeffutter** [zipmark/rspec_api_documentation#232]
The documentation on the front page shows using headers inside of a `do` block. If I do this then `headers` inside of the example block is `nil`. Also evaluating the output of do_request it appears to not use the header. Using the header outside of the do block works as expected.

I was wondering if the header inside the `do` block is supposed to work? If not I can open a PR to correct the documentation.

**Comment by oestrich** [comment]
Just tested this and it looks like it's working for me. Can you post an example of it failing?

**Comment by oestrich** [comment]
Closing due to age.
