### ISSUE TITLE
Api Blueprint format

### ISSUE THREAD

**Issue by alexandrz** [zipmark/rspec_api_documentation#235]
Please, add api blueprint output format. The specification can be found here - https://apiblueprint.org/

**Comment by ceritium** [comment]
Hi, I am working for support swagger, probably you could use https://apitransformer.com/ for transform the outoput.

**Comment by alexandrz** [comment]
@ceritium great! thank you for the link

**Comment by ceritium** [comment]
@alexandrz, do you know this? https://github.com/calderalabs/rspec_api_blueprint/

**Comment by alexandrz** [comment]
@ceritium no. Thank you, will check it

**Comment by alexandrz** [comment]
@ceritium btw apitransformer didn't help. I tried to convert from I/O Docs format to Blueprint and got an error.

**Comment by ceritium** [comment]
@alexandrz I mean use the swagger output and transform it to blueprint.

**Comment by oestrich** [comment]
Echoing my comments from #216, I'll merge a PR that adds support of Api Blueprint. I don't use it so I have no intentions of adding support myself.

**Comment by kurko** [comment]
I'm working on this. The caveat here is that BlueprintAPI is not navigable like HTML with index+page with details, therefore my plan is to have just one `.apib` file with the entire generated spec. I could build an HTML index pointing to the `.apib` files but usually we do want the entire spec in one single APIB file to be able to use all the tools it has around it (e.g dredd etc). PR coming.
