### ISSUE TITLE
required relationship needs valid ID passed in params

### ISSUE THREAD

**Issue by h55nick** [zipmark/rspec_api_documentation#237]
Hello! Thanks for supplying this, we are starting to use this more heavily to create json to power our documentation but I am running into a problem.

Setup:
a comment requires an author 

when trying:
 ```
post '/api/comment' do
  let(:author) { create(:author) }
  parameter :author_id, 'the authors id', scope: :comment
  let(:author_id) { author.id }

  it 'creates a comment with an author' do
    do_request
    expect(response_status).to eq(200)
  end 
end 
```

I am having trouble making sure the 'author' in which the parameter: author_id is set to still exists when running the request. Any ideas?

**Comment by oestrich** [comment]
What does your controller look like? The current setup posts the param to `params[:author_id]`. If you're pulling comment attributes out of `params[:comment]` it will be missing.

**Comment by h55nick** [comment]
sorry, it does have the correct scope.  `scope: :comment` (will update example)

I think the problem might be the database cleaner cleans out everything in the 'describe'/'post' before the example runs, allowing the id to be passed correctly but not reference any object in the database.

**Comment by oestrich** [comment]
@h55nick Is this still an issue? I will reopen if it is.

**Comment by h55nick** [comment]
We found a work around I believe and will reopen if it becomes untenable. Thanks.
