### ISSUE TITLE
rename post_body_formatter to request_body_formatter

### ISSUE THREAD

**Issue by galiat** [zipmark/rspec_api_documentation#243]
Just a thought, but in the config, `post_body_formatter` also formats the body for `put` & `patch` so maybe it should be re-named. I'd be happy to rename it to `request_body_formatter` with backwards compatibility to support those who currently use `post_body_formatter`.

**Comment by oestrich** [comment]
I think this makes sense. :+1:

**Comment by oestrich** [comment]
Closing because of #244
