### ISSUE TITLE
Skip generating documentation for few examples

### ISSUE THREAD

**Issue by navaneeth** [zipmark/rspec_api_documentation#246]
Hi,

I have started using this gem for generating API documentation. All works well so far. Is there a way to skip some examples appearing the documentation? I tried `no_doc`, but that can be used inside examples. The example still shows up in the document. 

In my case, I'd like to skip all the tests cases which tests parameter validations, errors etc appear in the documentation. Any way to do this?

**Comment by oestrich** [comment]
You can set `:document => false` as part of the example's metadata.

``` ruby
context "validations", :document => false do
  # ...
end
```
