### ISSUE TITLE
nothing is generated. 

### ISSUE THREAD

**Issue by MaxPleaner** [zipmark/rspec_api_documentation#247]
I have specs in the /spec/ folder of my rails app. When I run `rake docs:generate` the index file is empty;.

**Comment by oestrich** [comment]
Do you have them in `spec/acceptance`? The rake task looks only inside that folder.

**Comment by MaxPleaner** [comment]
I thought this might be the case. I looked in the config options for a place to change that and didn't see anything, though. I guess I can move my specs to /acceptance, dont see why it should matter though.

**Comment by oestrich** [comment]
They need to be in that folder because this task only looks there. You're welcome to write your own or do what it does. The rake task is just a nicety.

https://github.com/zipmark/rspec_api_documentation/blob/master/lib/tasks/docs.rake#L5
