### ISSUE TITLE
Which is preferred, let() vs alternatives

### ISSUE THREAD

**Issue by sbwoodside** [zipmark/rspec_api_documentation#248]
I could do 

    parameter :email, "User email"
    example "Creating an account", :document => :private do
      do_request(:email => "eric@example.com")

or

    parameter :email, "User email"
    let(:email) { "eric@example.com" }
    example "Creating an account", :document => :private do
      do_request()

Which is preferred?

**Comment by oestrich** [comment]
I don't think there is a preferred version. I tend to do `let` so I can use `example_request` which triggers the do_request for you.

**Comment by sbwoodside** [comment]
Oh OK I didn't understand that part of example_request before.

It seems as though it might be useful to either allow parameter to include let, something like

    parameter :email, "User email", :let => "eric@example.com"

And then the docs could include the "eric@example.com" as an example of what the value can be.

**Comment by oestrich** [comment]
Whatever you place after the description will show up in the the JSON or HTML docs that get generated, so if you want to do `:default => "eric@example.com"` you can. Users can also look at the request/response that actually happened to get an idea of sample data.

We went with the let version so you could override via contexts. If you want to write a PR that does it via the parameter line, I'm not opposed.

**Comment by sbwoodside** [comment]
ok thanks
