### ISSUE TITLE
Broken nested scoping

### ISSUE THREAD

**Issue by ralphie02** [zipmark/rspec_api_documentation#256]
I believe scope nesting for the api request parameters are either not properly documented, or broken.
I am trying to do something similar to below:

```
get '/api/something" do
  parameter :person, "description", scope: :company
  parameter :name, "description", scope: [:company, :person]
end
```

for a parameter like this -> `company[person][name]`

but instead it creates something similar to this -> `[:company, :person][name] [:company, :person][name]`
and yes, there's 2 of the parameter names above this line

I could definitely be wrong and that this feature is already implemented, I'm just using it wrong. If I am, please let me know.

**Comment by oestrich** [comment]
What are you using to view the documentation? There is a good chance they just need to be updated to understand the new scopes.

**Comment by ralphie02** [comment]
I'm not using any specific viewer such as the ones mentioned in your documentation. I'm just viewing the simple HTML file generated by `rake docs:generate`

Is there a workaround for this?

**Comment by DevilsNightsix** [comment]
@ralphie02 You need to install Apitome from github master branch
add to your ```Gemfile```

```ruby
gem 'apitome', github: 'modeset/apitome'
```

**Comment by ralphie02** [comment]
@DevilsNightsix I was hoping I didn't have to install any doc viewer. Thanks for getting back to me!

**Comment by myabc** [comment]
I can confirm that this is still broken on `master` 

`response_field :id, 'Feedback ID', scope: [:comment, :feedback]`

will render the following with both `HtmlWriter` and `SlateWriter`:

`[:comment, :feedback][[:comment, :feedback][id]]	`

**Comment by DevilsNightsix** [comment]
Hello @myabc 
I have made fix for this issue
If you want, you can use my fork of [Apitome](https://github.com/DevilsNightsix/apitome)

**Comment by myabc** [comment]
@DevilsNightsix I'm not actually using Apitome, but thanks anyway!
