### ISSUE TITLE
Compatibility with rspec 3.5.0 / Rails 5

### ISSUE THREAD

**Issue by micred** [zipmark/rspec_api_documentation#263]
I've upgraded my project to Rails 5.0.0.beta2 / rspec 3.5.0.beta1 without any significant issue.
The bad news is that rspec_api_documentation depends on rspec ~> 3.0.

I've no knowledge of rspec internals, so I'm asking: is it safe to use rspec_api_documentation with rspec 3.5? 
_Apparently_ it works  https://github.com/micred/rspec_api_documentation but I don't submit a PR since I have no knowledge of rspec as I said.

**Comment by oestrich** [comment]
I think this the gem is failing to install with the beta because of `.beta2`. The tilde operator must know know what to do with that. Once 3.5.0 is released RAD should just work it with.
