### ISSUE TITLE
Feature Request/ Confirmation - Check for pending migration

### ISSUE THREAD

**Issue by Shwetakale** [zipmark/rspec_api_documentation#270]
When we run 

```
rake docs:generate
```

Can we check if there are any pending migrations like rspec does.

**Comment by Shwetakale** [comment]
@oestrich Do we need this feature? I would like to look into this if possible.

**Comment by oestrich** [comment]
`rake docs:generate` is an RSpec rake task it should do the same migration check. If it doesn't work for you, then I'll gladly look at a PR for whatever you find out.

**Comment by Shwetakale** [comment]
Yes it doesn't work for me on version ```4.6.0```. I will once check it on latest version.

**Comment by oestrich** [comment]
Closing due to age.
