### ISSUE TITLE
How to get exception information?

### ISSUE THREAD

**Issue by alexandrz** [zipmark/rspec_api_documentation#271]
I have a failing spec:

```
     Failure/Error: expect(status).to eq 200
       
       expected: 200
            got: 500
       
       (compared using ==)
```

How can I tell rspec_api_documentation to return exception itself instead of response with 500 code?

**Comment by jakehow** [comment]
@alexandrz these are full stack tests, your exceptions are probably getting logged to test.log so you can get them there, but if you are returning the exception in the body of the response, you can just assert on body before you assert on the status code.

As an alternative, if you just need to see it temporarily for debugging purposes, what I normally do is log the body or print it to the console (or insert a debugger prior to the assertion that is failing).

so you'd have code like this:

```ruby
puts response_body
expect(status).to eq 200
```

and you would delete the puts once you get your endpoint working correctly.

**Comment by alexandrz** [comment]
It only happens on a build service I don't have access to, I can't reproduce it locally. In my opinion, it would be better if it raised an exception giving more information about the actual error. At least it would be great to configure this behavior.
