### ISSUE TITLE
Is it possible to define headers for all requests and filter out specific headers from generated files?

### ISSUE THREAD

**Issue by knovoselic** [zipmark/rspec_api_documentation#273]
Hi,

I'm testing this tool and really liking it so far. I have two separate questions:

is it possible to define headers for all requests? E.g. I'd like all my acceptance specs to have the following headers defined:

    header 'Accept', 'application/json'
    header 'Content-Type', 'application/json'

And is it possible to hide specific headers from generated docs? It would be the opposite of existing `config.request_headers_to_include` option.

**Comment by marnen** [comment]
I'd very much like the ability to define global headers too. Should I just put them in an `around(:all)`, or is there a better way?

**Comment by knovoselic** [comment]
Here's how I've implemented this:

I've created a `spec/acceptance_helper.rb` file:
```ruby
require 'rails_helper'
require 'rspec_api_documentation/dsl'

RSpec.configure do |config|
  config.before(:each) do |spec|
    if spec.metadata[:type].equal? :acceptance
      header 'Accept', 'application/json'
      header 'Content-Type', 'application/json'
    end
  end
end
```

and in each acceptance spec instead of requiring:
```ruby
require 'spec_helper'
require 'rspec_api_documentation/dsl'
```
I just require:
```ruby
require 'acceptance_helper'
```

**Comment by FrankFang** [comment]
Thanks!
