### ISSUE TITLE
Interest in Slate writer?

### ISSUE THREAD

**Issue by marnen** [zipmark/rspec_api_documentation#275]
For a project at my job, I'm customizing the Markdown writer so it can output nicely to [Slate](https://github.com/tripit/slate). I suspect others have this need too, so would a pull request with a SlateWriter class be of interest? Or would that do better in a separate gem that depends on this one?

**Comment by oestrich** [comment]
I haven't seen Slate before, but it looks nice. I am interested in a SlateWriter and would be up for merging a PR with it.

**Comment by marnen** [comment]
Great. I'll try to package what I've done.

**Comment by jakehow** [comment]
@marnen we use slate for some of our stuff.  Let us know when you put up a branch and we will check it out.

**Comment by BenMorganIO** [comment]
I've got a good working engine done over at https://github.com/wildcardlabs/apitome_slate. I could make a PR to add it to the readme?

@marmen does this repo help?

Example from my end:

![screen shot 2016-04-25 at 3 48 47 pm](https://cloud.githubusercontent.com/assets/3117356/14801315/3da44bba-0afd-11e6-9d8b-393683871ab4.png)

**Comment by marnen** [comment]
@BenMorganIO From your screenshot, that looks like it may be fairly similar to the work I did. I'll hopefully have time on Thursday to make that public.

**Comment by marnen** [comment]
Working on this now.

**Comment by marnen** [comment]
See #282!

**Comment by marnen** [comment]
See #282! (Especially tagging @jakehow and @BenMorganIO).

**Comment by rpocklin** [comment]
I think this issue has been solved by #282
