### ISSUE TITLE
`document: false` doesn't work

### ISSUE THREAD

**Issue by justinko** [zipmark/rspec_api_documentation#276]
Need to use `fetch` [here](https://github.com/zipmark/rspec_api_documentation/blob/master/lib/rspec_api_documentation/dsl.rb#L24).

**Comment by Shwetakale** [comment]
@justinko Which gem version are you using? I am using ```4.6.0``` and it works.

**Comment by brateq** [comment]
But in 4.8.0 it doesn't work.

**Comment by brateq** [comment]
4.9.0 works again :)

**Comment by oestrich** [comment]
This should be fixed now with #351
