### ISSUE TITLE
empty doc file

### ISSUE THREAD

**Issue by tokhi** [zipmark/rspec_api_documentation#280]
I have all my rspec tests in `spec/requests/` directory and its looking something like this:
```
require 'rails_helper'
require 'rspec_api_documentation/dsl'

RSpec.describe "V1::Verticals", :type => :request do

  let(:headers) { {} }
  context 'Create new vertical context' do
    let(:params){ attributes_for(:vertical) }
    subject { post verticals_path, {:vertical=>params}, headers }
    it "creates a new vertical" do
      subject
      expect(response).to have_http_status(201)
    end
  end
```
When I try to generate rspec docs I get an empty file
```
{
  "resources": []
}
```
I even made my own `docs` rake task to look in the `requests` directory.
The generate task only works If I include the `resource` header:
```
resource "verticals" do
  get "/v1/verticals" do
    example "Listing verticals" do
      do_request
      status.should == 401
    end
  end
end
```

**Comment by oestrich** [comment]
You need to wrap everything inside of a `resource` or set the metadata yourself, see [dsl.rb](https://github.com/zipmark/rspec_api_documentation/blob/master/lib/rspec_api_documentation/dsl.rb#L22-L24)

**Comment by tokhi** [comment]
Wrapping everything inside a resource will bring more headaches for the rspec tests of type `request`, I am not sure how difficult is to find a solution for this dependency.
```
block in <top (required)>': undefined method `resource' for RSpec::ExampleGroups::V1Verticals:Class (NoMethodError)
```

**Comment by oestrich** [comment]
These aren't request specs. The example you listed won't actually run with RAD, it's different than normal request specs.
