### ISSUE TITLE
Check flash in http requests.

### ISSUE THREAD

**Issue by andriiNyzhnik** [zipmark/rspec_api_documentation#281]
Is it possible some how to check flash in http request?

**Comment by oestrich** [comment]
If you have something that can parse flash responses in ruby then you can use the gem. The documentation will most likely say `[binary data]` for the response.

**Comment by andriiNyzhnik** [comment]
And how I can retrieve that flash response?

**Comment by oestrich** [comment]
Via `response_body`, see the [readme](https://github.com/zipmark/rspec_api_documentation#response_body)

**Comment by andriiNyzhnik** [comment]
Rails flash from **responce_body**?

**Comment by oestrich** [comment]
Oh you're not talking about Adobe Flash. Can you explain how you're using the flash in an API?

**Comment by andriiNyzhnik** [comment]
For example I send post with some data to create an record. And I want to get some how session object to be able to retrieve flash messages.

**Comment by jakehow** [comment]
@andriiNyzhnik this project is primarily focused on API testing, in which case you would not be using flash messages.  If you are using flash messages in your API you should be putting them in a header, or in the response body, where you can check their values.

If you are using this to test an html page, you can also check that the flash message is rendered in the `response_body`

**Comment by andriiNyzhnik** [comment]
@jakehow the problem is with flash that has not been rendered in html page: e.x. redirect.
So currently, for testing html it is not possible to retrieve flash outside html page, am I right?

**Comment by andriiNyzhnik** [comment]
I don't use flash in api. I make just simple http requests.

**Comment by jakehow** [comment]
@andriiNyzhnik not clear to me what you are trying to do, but you should probably use response_body to check for the flash message.

**Comment by andriiNyzhnik** [comment]
Ok. You can close the issue.

**Comment by jakehow** [comment]
@andriiNyzhnik closing, if you need to you can follow the redirect and make a second request.
