### ISSUE TITLE
How to skip already generated docs?

### ISSUE THREAD

**Issue by Awatatah** [zipmark/rspec_api_documentation#285]
Hello, this works great but, how can I skip already generated .rspec files? Let's say I already ran and generated docs but I have to modify only 1, how can I generate where It only runs that one file and includes it into the already generated docs?

**Comment by oestrich** [comment]
What you want is this, https://github.com/zipmark/rspec_api_documentation#append_json. This format will let you keep the rest of the docs and only modify that one specs docs.

**Comment by Awatatah** [comment]
Awesome, thank you!
