### ISSUE TITLE
Cache Headers aren't avaible on headers

### ISSUE THREAD

**Issue by jflobos** [zipmark/rspec_api_documentation#293]
Hi,

I have an API that uses HTTP Caching, I cannot access using "headers" I look for a configuration misread or something but I can't find nothing about that.

For example my test:
```ruby
example "http_cache" do
      75.times { create(:event)}
      do_request
      expect(status).to eq(200)
      expect(headers).to include("Cache-Control")
      expect(headers).to include("Last-Modified")
end
```

Looking in the documentation there are a config for the headers that I modified but the headers doesn't appear.

My Rspec Api Documentation configuration:
```ruby
RspecApiDocumentation.configure do |config|
  config.api_name = "API Documentation"
  config.response_headers_to_include = ["Content-Type", "Cache-Control", "Etag"]
end
```

Using a normal Rspec test I cant access to response headers and the "Cache-Control" is avaible, but using DSL I can't access to the Caching headers.

It's is the normal behavior or I didn't configure the test.

**Comment by myabc** [comment]
@jflobos what happens if you comment out `response_headers_to_include`?

**Comment by jflobos** [comment]
Hi, 

Finally I found the problem, It was me, I was looking for the "**request**", when I must look for "**response_headers**". The response_headers are working fine.

This is the code without the problem:

```ruby
example "http_cache" do
      75.times { create(:event)}
      do_request
      p response_headers
      expect(status).to eq(200)
      expect(response_headers).to include("Cache-Control")
      expect(response_headers).to include("Etag")
end
```

Thanks!
