### ISSUE TITLE
How to generate with rails 5?

### ISSUE THREAD

**Issue by fuelen** [zipmark/rspec_api_documentation#302]
rake docs:generate
Running via Spring preloader in process 28533
rake aborted!
Don't know how to build task 'docs:generate' (see --tasks)

**Comment by oestrich** [comment]
Did you restart spring after installing the gem? The other possibility, did you include RAD in the development group?

**Comment by fuelen** [comment]
Yes. RAD is in the development group and spring was killed.

**Comment by gkunwar** [comment]
@fuelen Did you find the solution. It is working properly in my Rails5 project.

**Comment by fuelen** [comment]
I'm copying rake tasks to lib

**Comment by fuelen** [comment]
Hmm, now it works :)
