### ISSUE TITLE
Rspec stub not being cleaned up

### ISSUE THREAD

**Issue by galori** [zipmark/rspec_api_documentation#303]
I have a stub in a before block:

```ruby
resource 'List' do

  header 'Content-Type', 'application/json'

  before do
    allow(YAML).to receive(:load_file).and_return({list: list_data})
  end
```

and it works fine, but it sticks around for subsequent specs and it is causing my model specs to fail. If I exclude this spec this doesn't happen.

I tried adding:

```ruby
  after do
    allow(YAML).to receive(:load_file). and_call_original
  end
```

but that doesn't even work, not sure why.

Shouldn't the standard rspec teardown happen?

**Comment by oestrich** [comment]
Yeah, we're not doing anything to before/after blocks. `resource` just sets up metadata a little then calls `describe`. I can't look into what might be the issue, but I'd welcome a PR or further investigation for when I do have time.

**Comment by galori** [comment]
Thanks for the quick response, I appreciate it.

> Yeah, we're not doing anything to before/after blocks

Meaning, this is not expected behavior and generally this pattern SHOULD work, correct?

If thats the case, I'll investigate further on my end and re-open if I know more and it warrants it. Thank you.
