### ISSUE TITLE
Generate from two rspec directories

### ISSUE THREAD

**Issue by evgenyneu** [zipmark/rspec_api_documentation#317]
Hi, is it possible to have tests that generate the docs in two directories `rspec/acceptance` and `rspec/another_dir`. Right now, the docs are built only form `rspec/acceptance` directory, and the tests in `rspec/another_dir` does not generate any documentation with `bundle exec rake docs:generate`. Thank you.

**Comment by oestrich** [comment]
You can define your own rake task for generation. For example:

```rake
require 'rspec/core/rake_task'

desc 'Generate API request documentation from API specs'
RSpec::Core::RakeTask.new('docs:generate') do |t|
  t.pattern = 'spec/{acceptance,another_dir}/**/*_spec.rb'
  t.rspec_opts = ["--format RspecApiDocumentation::ApiFormatter"]
end
```

This should load form both folders. I guessed at the pattern so it might not work. In that case you can always run the rspec command with the formatter directly.

```bash
rspec --format RspecApiDocumentation::ApiFormatter spec/acceptance spec/another_dir
```

**Comment by evgenyneu** [comment]
Thank you, @oestrich.
