### ISSUE TITLE
parameter :status result Rack::Test::Error

### ISSUE THREAD

**Issue by brateq** [zipmark/rspec_api_documentation#329]
```
get 'http://api.example.com/v1/users/current/' do
 parameter :status

  example 'List' do
    do_request
    expect(status).to eq 200
  end
```

This spec ends with error:

```
Failure/Error: do_request
     Rack::Test::Error:
       No response yet. Request a page first.
```

rspec_api_documentation 4.9.0
rspec 3.5.0 
rails 5.0.0.1

**Comment by oestrich** [comment]
Because you have a parameter named `status`, `do_request` is calling the `status` method which is where this is failing. You want to add this to your configuration:

```ruby
  config.disable_dsl_status!
```

You will need to use `response_status` instead.

**Comment by duleorlovic** [comment]
With `config.disable_dsl_status!`  I got error that status is not defined

````
     Failure/Error: expect(status).to eq(200)
     
     NameError:
       undefined local variable or method `status' for #<RSpec::ExampleGroups::Sessions::POSTApiV2SessionsUserLogin:0x0000000006439238>
       Did you mean?  status_code
```
How can I assert status code in this case ?

**Comment by duleorlovic** [comment]
I found that we can use `expect(response_status).to eq 200`.
I added a comment in README

**Comment by Isaac-alencar** [comment]
> Because you have a parameter named `status`, `do_request` is calling the `status` method which is where this is failing. You want to add this to your configuration:
> 
> ```ruby
>   config.disable_dsl_status!
> ```
> 
> You will need to use `response_status` instead.

thank you so much, I am literally fighting with this since 9 a.m! 😅 ❤️
