### ISSUE TITLE
Bug "with_options required: true" doesn't display "required" label

### ISSUE THREAD

**Issue by anthony-robin** [zipmark/rspec_api_documentation#331]
When using the `with_options required: true` block option, the `required` label doesn't show up on `apitome`. Using manually `required: true` works as expected.

```ruby
with_options required: true do
  parameter :email # Doesn't show required label
  ...
end

parameter :email, required: true # Show required label
```

**Comment by hughkelsey** [comment]
I know this is an old issue but I'm running version 5.1 and this is not an issue any longer

**Comment by jwg2s** [comment]
I think this may have flipped where everything is showing as required. Not sure if this is an RAD issue, or my lack of understanding of apib.

Text that gets generated without specifying `:required`
```
+ Parameters
  + first_name - First name for the user.
  + last_name - Last name for the user.
  + email - Email address for the user.
  + status - Status of the user. Can be set to &#39;active&#39; or &#39;inactive&#39;.
```

But `(required)` shows up next to all these when rendered.
