### ISSUE TITLE
request.env unavailable before tests

### ISSUE THREAD

**Issue by BagpipesJohnson** [zipmark/rspec_api_documentation#333]
I am trying to use rspec_api_documentation to an already existing set of tests for an API. I need to have HTTPS enabled, so I have the following block of code before any of my tests happen

`before(:each) { request.env['HTTPS'] = 'on' }`

This works in my tests. When trying to `rake docs:generate`, I get the following error:

` NameError:
        undefined local variable or method 'request' for #<RSpec::ExampleGroups::ApiV2AssignedTasksController::AssignedTasks::DeleteDestroy::WrongCompany:0x007feb2867af00>
        Did you mean?  require
`

My hunch is that this has something to do with the Gotchas mentioned at the bottom of the documentation. Any direction would be appreciated

**Comment by nozpheratu** [comment]
I too was trying to figure out how to accomplish this.

**Comment by oestrich** [comment]
There isn't a `request` object for RAD. There isn't a way to edit the `env` directly. You can only change headers that get sent. This is to make RAD more of an integration test and run through the full stack.

**Comment by nozpheratu** [comment]
@oestrich Is there a way to change the protocol via headers? `header 'Host', 'https://www.example.org'` for instance will produce a url like: `http://https://www.example.org` in the generated docs.

**Comment by oestrich** [comment]
You can configure your test environment to return https links

```ruby
config.action_mailer.default_url_options = {scheme: "https", host: "example.org"}
```
