### ISSUE TITLE
Format body request

### ISSUE THREAD

**Issue by sveredyuk** [zipmark/rspec_api_documentation#345]
There is some way how to format request's body by default HTML formatting?
Because such kind of formatting are not very well acceptable for eyes:
<img width="1025" alt="2017-05-30 12 18 41" src="https://cloud.githubusercontent.com/assets/5221643/26576660/5391d45e-4532-11e7-8321-3c5ea952b84a.png">

**Comment by oestrich** [comment]
Do you mean outside of a code block? I prefer the code block myself as it's at least monospaced. If your endpoint takes JSON input you can also send it up that way to get JSON formatting.

**Comment by sveredyuk** [comment]
@oestrich nope) I mean render to html doc formatted JSON instead query_string in body request section

**Comment by oestrich** [comment]
The body is exactly what is being sent up. If you want JSON you have to `#to_json` your post body.

```
header "Content-Type", "application/json"
let(:raw_post) { params.to_json }
```

**Comment by sveredyuk** [comment]
@oestrich exactly. thanks a lot!  👍
