### ISSUE TITLE
How to add description to a group

### ISSUE THREAD

**Issue by prikha** [zipmark/rspec_api_documentation#354]
Hi guys, unable to find an option to put any additional info for the whole group info. Is it possible? 

What I am looking for is something like this: 

```
config.define_group(:public) do |public|
    public.docs_dir = config.docs_dir + 'public/'
    public.api_name = "Public API Header"
    public.api_explanation = <<~EXP
... html markup for the into ...
EXP
    public.filter = :public
  end
```

is there a way to do this?

**Comment by oestrich** [comment]
There is not a way to do this currently. I'd be happy to review a PR if you added it though!

**Comment by prikha** [comment]
Ok, Im on it
ср, 16 авг. 2017 г. в 21:03, Eric Oestrich <notifications@github.com>:

**Comment by prikha** [comment]
@oestrich Sumbmitted #356, would you mind to take a look
