### ISSUE TITLE
Input Folder Setting?

### ISSUE THREAD

**Issue by 3DEsprit** [zipmark/rspec_api_documentation#358]
I have been curious about an option to change the spec test input, but looking at the documentation on the task it looks like it is hard-coded to look in /spec/acceptance. Instead of creating another task, is there a better option to change this?

**Comment by oestrich** [comment]
Creating another task is definitely the easiest way to change what folder you want to load. You can also invoke rspec with the files you want and add on `--format RspecApiDocumentation::ApiFormatter` to generate documentation.

**Comment by 3DEsprit** [comment]
Yes this has been working well for me since I posted this question, but I initially misunderstood the purpose of this project. Seeing it in an acceptance/request type test my initial thought was to replace request tests, and receive documentation at the same time like how the old swagger-docs works with existing controllers, but that does not seem to be the fact at all. 

Forcing these tests into an acceptance folder allows for the rspec default request folder to have its tests, and the documentation to have its own as well. My apologies for not picking up on that before this post.
