### ISSUE TITLE
Ability to override response_body_formatter per test?

### ISSUE THREAD

**Issue by eklamer** [zipmark/rspec_api_documentation#360]
I have two separate specs. One spec has complex batch updating logic with a hundred fields that I don't need in my examples, so I am using this config to iterate over the response_body and call a class method to slice out some unnecessary fields.

However, all the other spec files now have this option set which causes them to return nothing at all for the generated JSON for the docs. Setting it back to 
`RspecApiDocumentation.configure do |config|
    config.response_body_formatter = :json
  end`
has no effect. It uses only the last one that was set regardless of when it was changed.

Is there a proper way to define these options per test or a better way to handle formatting the response_body whenever and however I need to do it? Thanks in advance.

**Comment by eklamer** [comment]
Nevermind. It was my problem. I had a 
`before each: :customers_query` which is incorrect syntax.
Changing it to `before :each, :customers_query` fixed it. 

Thanks for the awesome gem.

**Comment by baixiaoji** [comment]
so this config is right?
```
RspecApiDocumentation.configure do |config|
   // ...
  config.response_body_formatter = :json
end
```
I see the doc is response body  is [binary data]

![image](https://user-images.githubusercontent.com/21168366/177662163-2e4ead86-6d15-4d3a-8e3c-0e2a4d0583f0.png)

rspec_api_documentation@6.1.0
