### ISSUE TITLE
Sending a json request to "show"?

### ISSUE THREAD

**Issue by GildedHonour** [zipmark/rspec_api_documentation#363]
How can I send a a) json request b) to "show" which expects an id? I've tried this:

```
resource "MyRes" do
  let(:item) { create(:item) }
  get "/trips", params: {id: 1, format: :json} do
    
    parameter :id, ""
    response_field :name, ""

    example_request "Get an item" do
      # ...........
```

But it returns html, although in "show" I have respond_to with json to and the route "items/1.json" works well.

**Comment by oestrich** [comment]
I think you're mixing up general controller tests with the DSL this gem uses. For html vs json, you either need to specify the `.json` in the url `get` uses or set the accept header. I would recommend the `Accept` header as it's more web standard. The `:id` also needs to be in the route that `get` accepts. Here is your example as I would expect it:

```ruby
resource "Trips" do
  header "Accept", "application/json"

  let(:trip) { create(:trip) }

  get "/trips/:id" do
    response_field :name, ""

    let(:id) { trip.id }

    example_request "Get a trip" do
      expect(status).to eq(200)
    end
  end
end
```

**Comment by GildedHonour** [comment]
Ok, but still:

       undefined method `create' for #<RSpec::ExampleGroups::Trips::GETTripsId:0x00005636101c8df0>


The factory "trip" exists.

```
FactoryGirl.define do
  factory :trip do
    name { Faker::Name.name }
  end
end
```

**Comment by GildedHonour** [comment]
up
