### ISSUE TITLE
Need to force client to make HTTPS requests

### ISSUE THREAD

**Issue by ErikPeterson** [zipmark/rspec_api_documentation#365]
The test environment for my application requires that all requests be made over https, and redirects any http requests made. It does not appear that there is any way to configure rspec_api_documentation to make request via https.

**Comment by oestrich** [comment]
If you need to go through the HTTPS layer you can use the http_test_client https://github.com/zipmark/rspec_api_documentation/blob/master/lib/rspec_api_documentation/http_test_client.rb which uses Faraday.

**Comment by ErikPeterson** [comment]
Thanks!

**Comment by ErikPeterson** [comment]
@oestrich if you have a moment could you elaborate on how to accomplish this? I've set `config.client_method = :http_test_client` but I can see that `rspec_api_documenation_client` still returns the RackTestClient struct. Happy to open a PR with documentation on this usage for the readme once I get it working, seems like something others might find useful

**Comment by Obiora-Imah** [comment]
@oestrich Please could you Elaborate on to accomplish the above suggestion you made on @ErikPeterson issue because i have similar issue
