### ISSUE TITLE
Unable to load `do_request` or `example_request` inside RSpec `shared_examples`

### ISSUE THREAD

**Issue by nitishmadhukar** [zipmark/rspec_api_documentation#380]
Versions:

- Rails 5.1.4
- RSpec 3.7
- RSpec API Documentation 5.1

I'm using RSpec `shared_examples` to test some common assertions across different API endpoints.

```
shared_examples 'something' do |param1, param2|
  get "/api/v1/#{param1}"
  example_request(param2)
  explanation 'Test explanation'
  expect(response_status).to eq 200
end
```

Im calling the above block using
`it_behaves_like 'something', 'testparam1', 'testparam2'`

The error generated is 

```
NoMethodError:
  undefined method `example_request' for RSpec::ExampleGroups::Metrics::BehavesLikeMetricsAPIInterface:Class
  Did you mean?  examples
```

Note: `explanation` method is loaded when I have a binding inside `shared_examples` but `example_request` does not load

**Comment by oestrich** [comment]
You want to write the shared example like this:

```ruby
shared_examples 'something' do |param1, param2|
  get "/api/v1/#{param1}" do
    example_request(param2) do
      explanation 'Test explanation'
      expect(response_status).to eq 200
    end
  end
end
```

`example_request` is only available inside the `get` block. The `explanation` that was loading was the higher up resource level explanation.

Thanks for being extremely thorough in your post! Let me know if this doesn't solve your issue.

**Comment by nitishmadhukar** [comment]
Awesome, I missed that `do` block inside `shared_examples`. Works now. 👏 

Thanks a lot for such a quick response. 👍
