### ISSUE TITLE
"Acceptance Specs" vs "Request Specs"

### ISSUE THREAD

**Issue by mattfordham** [zipmark/rspec_api_documentation#381]
I typically use [Request Specs](https://relishapp.com/rspec/rspec-rails/docs/request-specs/request-spec) to test my controllers. Are the "Acceptance Specs" provided by this library intended/suggested to be a replacement for "Request Specs", or an addition to them? Perhaps something has been written on the topic already and I missed it?

Thanks!

**Comment by oestrich** [comment]
I have previously used RAD for the full testing of my controllers but at this point I'd say go for only what you want to have documented. For instance just the happy path, and write a guide on types of errors the API in general will return and expand that with specific description on each endpoint if there are extra errors that might come back.

**Comment by mattfordham** [comment]
That's very helpful, thank you!
