### ISSUE TITLE
Generate Authorization header based on current request.fullpath

### ISSUE THREAD

**Issue by joustava** [zipmark/rspec_api_documentation#391]
I am struggling with a case in which I need to generate an Authentication header based on the current fullpath (e.g /search?search=value) that is going to be under test as e.g:
`header "Authorization", :auth_header

  let(:auth_header) {
    # do some setup
    generate_header(request.fullpath)
  }

  parameter :search, "search query"

  get "/search" do
     #... tests
`

Is there any way this is possible?

**Comment by oestrich** [comment]
At the moment you have to build this yourself. See https://github.com/zipmark/rspec_api_documentation/blob/master/lib/rspec_api_documentation/dsl/endpoint.rb#L45 for how the gem does it.

`"#{path}?#{query_string}"` should work for what you're looking for.

**Comment by joustava** [comment]
Nice, works like a charm. Thanks!
