### ISSUE TITLE
 api_blueprint without api_explanation

### ISSUE THREAD

**Issue by SrMouraSilva** [zipmark/rspec_api_documentation#394]
Could you please add `{{ api_explanation }}` to `api_blueprint_index.mustache`?

```
FORMAT: A1
# {{ api_name }}

{{ api_explanation }} <-----------

{{# sections }}
```

And also update the gem? In the currente released version, it does not come with `# {{api_name}}`  :cry: 

https://github.com/zipmark/rspec_api_documentation/blob/35bac0b4718d7bfbd5b92c7b09b89ff1cbca17d3/templates/rspec_api_documentation/api_blueprint_index.mustache#L2

My Gemfile 

```
[...]
group :development, :test do
  gem 'rspec-rails', '~> 3.5'
  gem 'rspec_api_documentation'
[...]
```

**Comment by oestrich** [comment]
That commit should be in the most recent version, 6.0.0. I released it on 8/23. There is no release calendar, it's whenever enough has built up and I remember to put a release out.

**Comment by SrMouraSilva** [comment]
I checked here and the rails had installed the previous version. I apologize for the mistake.

I'll merge request from https://github.com/zipmark/rspec_api_documentation/issues/394#issue-353480845

**Comment by SrMouraSilva** [comment]
I submit a merge request
