### ISSUE TITLE
Error using json format

### ISSUE THREAD

**Issue by abuzzany** [zipmark/rspec_api_documentation#411]
Hello, I just started to use this gem and I configured my `acceptance_helper.rb` like this in order to have json outputs:

```ruby
require "rails_helper"
require "rspec_api_documentation"
require "rspec_api_documentation/dsl"

RspecApiDocumentation.configure do |config|
    # Output folder
    config.docs_dir = Rails.root.join("doc", "api")
    config.format = :json
end
```

reading your Readme.md I found this to configure the format:

![screen shot 2018-10-03 at 12 05 43](https://user-images.githubusercontent.com/4792866/46426596-ae211380-c704-11e8-8d20-a779a28ada9b.png)

however when I exec rspec with `--format RspecAp
iDocumentation::ApiFormatter` I got the next error:

`NameError: uninitialized constant RspecApiDocumentation::Writers::JsonWriter`

I realized that If I use upcase instead of lower case for format configuration it works:

```ruby
RspecApiDocumentation.configure do |config|
    # Output folder
    config.docs_dir = Rails.root.join("doc", "api")
    config.format = :JSON
end
```

**Comment by oestrich** [comment]
This is a known problem and should be fixed on master. I can do a new release sometime soon since this is a common thing.

**Comment by oestrich** [comment]
Can you update to 6.1.0 and see if your issue is fixed?
