### ISSUE TITLE
Abstracting with_options and other parameters

### ISSUE THREAD

**Issue by Equable** [zipmark/rspec_api_documentation#436]
I've been trying to find a way to abstract the `parameters` or `with_options`. Im not sure if this is intentional but I am unable to put them in a before each or a helper method to be used. Right now I have to copy paste the parameters in each type of put, post, patch etc. and its bulking the code considerably.

Is there a way around this?

**Comment by jakehow** [comment]
@Equable can you provide a specific example of what you want to do and what you are currently stuck doing?

**Comment by Equable** [comment]
Here's an example. 

```
post 'some address' do
    explanation 'POST'
    parameter :id, 'ID', required: true

    with_options scope: :some_model, with_example: true, required: true do
      parameter :date
      parameter :distance
      parameter :distance_unit
    end

    context '200' do
      example 'POST <some address>' do
        request = attributes_for(:some_model)
        do_request(request)

        expect(status).to eq(200)
      end
    end
end

patch 'some address' do
    explanation 'PATCHES'
    parameter :id, 'ID', required: true

    with_options scope: :some_model, with_example: true do
      parameter :date
      parameter :distance
      parameter :distance_unit
    end

    context '200' do
      example 'PATCH <some address>' do
        request = attributes_for(:some_model)
        do_request(request)

        expect(status).to eq(200)
      end
    end
end
```

I would like to avoid having to copy and paste reused parameters like with_options since some of the routes im created has over 10 parameters.

When i try to put it in a before or helper method I get an error telling me it has to be in an example, then when i put it in an example it tells me it has to be in a describe or before

**Comment by Equable** [comment]
Anything on this?

**Comment by jakehow** [comment]
@Equable while I think this sort of duplication is probably not something I'd want to abstract away, I can think of two approaches that would probably work.

1.  Write a helper method that takes the context as an arg or put it in, ex:
```ruby
def setup_endpoint(context)
  #do stuff
end
```

Call it from your example group like: `setup_endpoint(self)`

2. Put the functionality in a module and mix it in to your example groups,  this is how RAD works internally.
