### ISSUE TITLE
Can we please opt-in to Hacktoberfest? 🙏🏻

### ISSUE THREAD

**Issue by davidstosik** [zipmark/rspec_api_documentation#483]
Not gonna lie, [Hacktoberfest](https://hacktoberfest.digitalocean.com/) is what got me back here at the beginning of the month. I didn't really have any plan to contribute to open source projects at this time, but seeing it and trying to find loose ends in my GitHub notifications, I got motivated to get back to work and submitted a few PRs.

Although at first the event didn't need any opt-in from maintainers, spam became so overwhelming that now [maintainers need to opt-in](https://hacktoberfest.digitalocean.com/hacktoberfest-update), either at the repository level (by adding the `hacktoberfest` topic), or at the PR level (by tagging each legit PR with `‘hacktoberfest-accepted`).

I'm thinking of submitting more work to this repository, but would very much appreciate if the work I provided so far could count, one way or the other, towards the Hacktoberfest goals. 🙏 

If I were a maintainer, I'd probably opt for tagging individual PRs with `hacktoberfest-accepted`, so that I don't open the whole repo to spammers who would think they've got a chance if the repo is tagged.

**Comment by jakehow** [comment]
@davidstosik I just created a `Hacktoberfest-accepted` label.  I just need that to any PRs made this month?

**Comment by davidstosik** [comment]
@jakehow Thank you and yes please! 🙏

**Comment by jakehow** [comment]
Sounds good 👍

**Comment by davidstosik** [comment]
@jakehow Could you please add the tag to these 4 PRs, when you have a minute? 🙏 

- #479 
- #480
- #481
- #482
