### ISSUE TITLE
How To: Run tests in parallel and generate documentation

### ISSUE THREAD

**Issue by bf4** [zipmark/rspec_api_documentation#502]
I figure this must be a solved problem, but I'm not sure how people manage it. Our suite runs a lot faster in parallel, but we still need to run it on one node to generate documentation. Is this solved in some way?

**Comment by jakehow** [comment]
@bf4 in the past we would run tests in parallel for CI/CD purposes and then run w/ the doc generation on a specific event like  branch merging or point release.  I think running in parallel while generating docs is possible but you'd need an adapter that runs as a separate service to collate the incoming streams from each node running that's producing docs.

**Comment by bf4** [comment]
Thanks @jakehow 

Right now our CI process is to 1) run tests in parallel 2) build the docs and commit if they may have changed 3) push to a deploy branch

I've been thinking about, if I cannot generate them in parallel, how to push the docs out separately from the main release

probably is parallel CI might take 15 minutes but full run takes over an hour
