### ISSUE TITLE
DSL discussion: expected attributes

### ISSUE THREAD

**Issue by claudiob** [zipmark/rspec_api_documentation#76]
In the same way that the DSL ensures that the API is called with the right parameters (required or not), have you ever thought of adding an **expected_attributes** method?

If your API returns a JSON, wouldn't it be nice to know (and to enforce with _rspec_) which attributes are returned and (at least) their type?

To make a comparison, it would like having on the [Github API orgs page](http://developer.github.com/v3/orgs/) not only _one single example of the response_: 

```
[
  {
    "login": "github",
    "id": 1,
    "url": "https://api.github.com/orgs/github",
    "avatar_url": "https://github.com/images/error/octocat_happy.gif"
  }
]
```

but a documentation specifying that the organization object returned by the API always has:
- login: string
- id: integer
- url: string
- avatar_url: string

The documentation might then add some more value to these attributes, explaining in words what they are, and what their characteristics are (example: if they can be null, what is their maximum size, etc.).

What is your opinion on this?

**Comment by chrishough** [comment]
@claudiob @oestrich I know this is an older issue, but I find myself researching exactly the same thing.  I am looking for a way to describe each field returned in my API json packets.  Has anything like this been added or forked from this project?

**Comment by claudiob** [comment]
@chrishough Tell me if this is what you're looking for: http://rspec-api.github.io/

**Comment by chrishough** [comment]
@claudiob that looks very close.  Does it have a way to describe each json attribute returned?

**Comment by claudiob** [comment]
@chrishough From the first example:

```ruby
has_attribute :id, type: {number: :integer}
has_attribute :where, type: :string
has_attribute :website, type: [:null, string: :url]
```

That means that the API will return a JSON which includes an `id` attribute (of JSON type number, specifically an integer), a `where` attribute (of JSON type string) and a `website` attribute (either of JSON type null or of JSON type string, specifically in a URL format)
